version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ans
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ans_dados
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: ans_app
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
      - ./dados_ans:/app/dados_ans
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=ans_dados
    working_dir: /app
    command: >
      sh -c "python teste3_bancoDeDados.py"

volumes:
  mysql_data: