version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ans_data:/app/dados_ans
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3307
      - MYSQL_DATABASE=ans_dados
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ans_dados
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
  ans_data: